- name: Update and upgrade Homebrew
  shell: brew update && brew upgrade && brew cleanup

- name: Install Java with Homebrew cask
  homebrew_cask:
    name: java8

- name: Install pip
  easy_install:
    name: pip
    state: latest
  become: yes

- name: Tap emacs-plus
  homebrew_tap:
    name: d12frosted/emacs-plus

- name: Tap fonts
  homebrew_tap:
    name: homebrew/cask-fonts

- name: Install libraries with Homebrew
  homebrew:
    state: latest
    name:
      - awscli
      - awsebcli
      - bash-completion
      - boot-clj
      - direnv
      - emacs-plus
      - heroku/brew/heroku
      - flyway
      - go
      - hugo
      - imagemagick
      - leiningen
      - lumo
      - markdown
      - macvim
      - maven
      - openssh
      - packer
      - postgresql
      - pipenv
      - pyenv
      - rbenv
      - rlwrap
      - terraform
      - the_silver_searcher
      - tmux
      - vcprompt
      - watchman
      - wget
      - yarn

- name: Source Code Pro Font
  homebrew_cask:
    name: font-source-code-pro
  become: yes

- name: Install libraries with Homebrew Cask
  homebrew_cask: name={{ item }} state=present
  with_items:
   - aerial
   - android-studio
   - font-source-code-pro
   - google-chrome
   - intellij-idea
   - ngrok
   - phantomjs
   - pycharm
   - skype
   - slack
   - spotify
   - vagrant
   - virtualbox
   - vlc

- name: Creates .nvm directory
  file:
    path: ~/.nvm
    state: directory

- name: nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
  args:
    creates: "~/.nvm/nvm.sh"
