- name: Update and upgrade Homebrew
  shell: brew update && brew upgrade && brew cleanup

- name: Install Java with Homebrew cask
  homebrew_cask:
    name: java8

- name: Install pip
  easy_install:
    name: pip
    state: latest
  become: yes

- name: Install libraries with Homebrew
  homebrew:
    state: latest
    name:
      - awscli
      - awsebcli
      - bash-completion
      - boot-clj
      - direnv
      - heroku/brew/heroku
      - flyway
      - go
      - imagemagick
      - leiningen
      - lumo
      - markdown
      - macvim
      - maven
      - nvm
      - packer
      - postgresql
      - pipenv
      - pyenv
      - rbenv
      - rlwrap
      - terraform
      - the_silver_searcher
      - tmux
      - vcprompt
      - watchman
      - wget
      - yarn
    
- name: Install openssh with Homebrew
  homebrew: name=openssh state=latest install_options=with-keychain-support

- name: Install libraries with Homebrew Cask
  homebrew_cask: name={{ item }} state=present
  with_items:
   - android-studio
   - google-chrome
   - intellij-idea
   - ngrok
   - phantomjs
   - pycharm
   - skype
   - slack
   - spotify
   - vagrant
   - virtualbox
   - vlc
