- name: install dependencies
  dnf: name={{ item }}
  with_items:
    - awscli
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
    - unzip
    - vagrant
    - '@Development Tools'
    - '@C Development Tools and Libraries'
  become: true

- name: download ngrok
  unarchive:
    src: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
    dest: ~/bin
    remote_src: true
  become: true
