- name: Tap Homebrew repositories
  homebrew_tap: name={{ item }} state=present
  with_items:
    - caskroom/cask
    - homebrew/binary
    - homebrew/completions
    - homebrew/dupes
    - homebrew/versions

- name: Update and upgrade Homebrew
  shell: brew update && brew upgrade && brew cleanup

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - awscli
    - awsebcli
    - bash-completion
    - boot-clj
    - direnv
    - heroku
    - imagemagick
    - lumo
    - markdown
    - nvm
    - packer
    - postgresql
    - pyenv
    - rbenv
    - rlwrap
    - terraform
    - the_silver_searcher
    - tmux
    - watchman
    - wget
    - yarn
    
- name: Install openssh with Homebrew
  homebrew: name=openssh state=latest install_options=with-keychain-support

- name: Install libraries with Homebrew cask
  homebrew_cask: name={{ item }}
  with_items:
   - android-studio
   - google-chrome
   - java
   - intellij-idea
   - ngrok
   - skype
   - spotify
   - transmission
   - vagrant
   - virtualbox
   - vlc
   
- name: Install Java libs
  homebrew: name={{ item }} state=latest
  with_items:
    - flyway
    - leiningen
    - maven

- name: Install Apex
  command: curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sh
