- name: Tap Homebrew repositories
  homebrew_tap: name={{ item }} state=present
  with_items:
    - caskroom/cask
    - homebrew/binary
    - homebrew/completions
    - homebrew/dupes
    - homebrew/versions

- name: Update and upgrade Homebrew
  shell: brew update && brew upgrade && brew cleanup

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - direnv
    - markdown
    - node
    - postgresql
    - rbenv

- name: Install openssh with Homebrew
  homebrew: name=openssh state=latest install_options=with-keychain-support

- name: Install libraries with Homebrew cask
  homebrew_cask: name={{ item }}
  with_items:
   - google-chrome
   - java
   - intellij-idea
   - ngrok
   - virtualbox
   - vagrant

- name: Install Java libs
  homebrew: name={{ item }} state=latest
  with_items:
    - flyway
    - leiningen
    - maven

