- name: install emacs config
  git:
    repo: git@github.com:stuartrexking/emacs.d.git
    dest: ~/.emacs.d
    force: yes
    
- name: install emacs
  dnf:
    name: emacs
    state: latest
  become: true 
