- name: install emacs config
  git:
    repo: git@github.com:stuartrexking/emacs.d.git
    dest: ~/.emacs.d
    force: yes

- name: Update and upgrade Homebrew
  shell: brew update && brew upgrade && brew cleanup

- name: Install emacss with Homebrew cask
  homebrew_cask: name=emacs

- name: Install cash with Homebrew
  homebrew: name=cask

- file:
    path: ~/Workspaces/emacs
    state: directory
    
- name: install neotree
  git:
    repo: git@github.com:jaypei/emacs-neotree.git
    dest: ~/Workspaces/emacs/neotree
    force: yes
    version: dev
    
- name: install helm
  git:
    repo: https://github.com/emacs-helm/helm.git
    dest: ~/Workspaces/emacs/helm
    force: yes

# needed for helm
- name: install async
  git:
    repo: https://github.com/jwiegley/emacs-async.git
    dest: ~/Workspaces/emacs/async
    force: yes

- name: make helm
  shell: /usr/bin/make
  args: 
    chdir: ~/Workspaces/emacs/helm