- name: install emacs config
  git:
    repo: git@github.com:stuartrexking/emacs.d.git
    dest: ~/.emacs.d
    force: yes
    
- name: install emacs
  dnf:
    name: emacs
    state: latest
  become: true 

- file:
    path: ~/Workspaces/emacs
    state: directory
    
- name: install neotree
  git:
    repo: git@github.com:jaypei/emacs-neotree.git
    dest: ~/Workspaces/emacs/neotree
    force: yes
    version: dev
