- name: install emacs config
  git:
    repo: git@github.com:stuartrexking/emacs.d.git
    dest: ~/.emacs.d
    force: yes
    
- name: install emacs
  dnf:
    name: emacs
    state: latest
  become: true 

- file:
    path: ~/Workspaces/emacs
    state: directory
    
- name: install neotree
  git:
    repo: git@github.com:jaypei/emacs-neotree.git
    dest: ~/Workspaces/emacs/neotree
    force: yes
    version: dev
    
- name: install helm
  git:
    repo: https://github.com/emacs-helm/helm.git
    dest: ~/Workspaces/emacs/helm
    force: yes

# needed for helm
- name: install async
  git:
    repo: https://github.com/jwiegley/emacs-async.git
    dest: ~/Workspaces/emacs/async
    force: yes
# run make after
