- name: install ruby
  dnf: ruby
  become: true

- name: install rbenv
  git:
    repo: ssh://git@github.com:rbenv/rbenv.git
    dest: ~/.rbenv

- name: install ruby-build
  git:
    repo: ssh://git@github.com:rbenv/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build

- name: install ruby dependencies
  dnf: name={{ item }}
  with_items:
    - openssl-devel
    - readline-devel
    - zlib-devel
