- name: check if slack is installed
  command: dpkg-query -W slack-desktop
  register: slack_check_deb
  failed_when: slack_check_deb.rc > 1
  changed_when: slack_check_deb.rc == 1

- name: download slack
  get_url: url=https://downloads.slack-edge.com/linux_releases/slack-desktop-2.5.1-amd64.deb
           dest=/tmp/slack.deb
  when: slack_check_deb.rc == 1

- name: install slack
  apt: deb=/tmp/slack.deb
  become: true
  when: slack_check_deb.rc == 1

- name: delete slack deb
  file: state=absent
        path=/tmp/slack.deb